@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.example.restaurant.models.Order#getTotalPrice()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.example.restaurant.models.Order",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1322970774 { 
   	label=example
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_390647231 { 
   	label=restaurant
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1107683126 { 
   	label=Order
	labeljust=l
	fillcolor=white
	style=filled
   
   Order384064374XXXgetTotalPrice0[
	label="+ getTotalPrice()"
	style=filled
	fillcolor=white
	tooltip="Order

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_1153278461 { 
   	label=CommonClient
	labeljust=l
	fillcolor=white
	style=filled
   
   CommonClient1091553721XXXhandlerRequest76453678[
	label="+ handlerRequest()"
	style=filled
	fillcolor=white
	tooltip="CommonClient

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1806762365 { 
   	label=Handler
	labeljust=l
	fillcolor=white
	style=filled
   
   Handler1091553721XXXhandlerRequest76453678[
	label="+ handlerRequest()"
	style=filled
	fillcolor=white
	tooltip="Handler

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_270379296 { 
   	label=FrequentClient
	labeljust=l
	fillcolor=white
	style=filled
   
   FrequentClient1091553721XXXhandlerRequest76453678[
	label="+ handlerRequest()"
	style=filled
	fillcolor=white
	tooltip="FrequentClient

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
CommonClient1091553721XXXhandlerRequest76453678 -> Handler1091553721XXXhandlerRequest76453678;
FrequentClient1091553721XXXhandlerRequest76453678 -> Order384064374XXXgetTotalPrice0;
Handler1091553721XXXhandlerRequest76453678 -> FrequentClient1091553721XXXhandlerRequest76453678;
    
}
@enduml